[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
zk_proof = "GwacL1YSrt8pAzZ5CupAHzzXAcwL65Wk2M4FUxM8fRGo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://solana-mainnet.g.alchemy.com/v2/ez0ou58DU8YEeS4MIErSOujrzcLPvn8m"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
